spring:
  application:
    name: /challengedropbox
  data:
    mongodb:
      host: localhost
      port: 27017
      database: dropbox
  jackson:
    time-zone: America/Sao_Paulo
    locale: pt-BR
    date-format: yyyy-MM-dd
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

server:
  error:
    include-message: "always"
  port: 9000
  servlet:
    context-path: /challengedropbox

# TODO setar dados servidor FTP
ftp:
  host: ""
  user: ""
  password: ""
  port: 21
