spring:
  application:
    name: /user-service
  data:
    mongodb:
      host: localhost
      port: 27017
      database: fitness
  jackson:
    time-zone: America/Sao_Paulo
    locale: pt-BR
    date-format: yyyy-MM-dd

server:
  error:
    include-message: "always"
  port: 9000
  servlet:
    context-path: /user-service
